---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  data_bags_path: test/fixtures/data_bags

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[vault_from_recipe::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
